- name: Create nginx namespace
  kubernetes.core.k8s:
    name: "{{ nginx_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Create nginx deployment
  kubernetes.core.k8s:
    state: present
    template: ../templates/deployment.yml.j2
    namespace: "{{ nginx_namespace }}"

- name: Create Load balancer for making nginx reachable from the internet
  kubernetes.core.k8s:
    state: present
    template: ../templates/loadBalancer.yml.j2
    namespace: "{{ nginx_namespace }}"
