---
- name: Create cloudWatch namespace
  kubernetes.core.k8s:
    state: present
    template: ../templates/namespace.yml.j2
    namespace: "{{ namespace }}"

- name: Create fluent-bit serviceAccount
  kubernetes.core.k8s:
    state: present
    template: ../templates/serviceAccount.yml.j2
    namespace: "{{ namespace }}"

- name: Create fluent-bit cluster-info as a configmap
  kubernetes.core.k8s:
    state: present
    template: ../templates/cluster-info.yml.j2
    namespace: "{{ namespace }}"

- name: Create fluent-bit configmap
  kubernetes.core.k8s:
    state: present
    template: ../templates/configmap.yml.j2
    namespace: "{{ namespace }}"

- name: Deploy fluent-bit agent as a daemoset
  kubernetes.core.k8s:
    state: present
    template: ../templates/daemonset.yml.j2
    namespace: "{{ namespace }}"